### ISSUE TITLE
Remote Desktop W1 W2

### ISSUE THREAD

**Issue by InaFricke** [InaFricke/SYS265FinalProject#25]
- [x] Create a Domain Group Policy that allows W1 + W2 to remote desktop between one another.
- [ ] Update RTVM

**Comment by InaFricke** [comment]
Stuck on proving it I cannot find the logs and gpresults does not show it

**Comment by echadbourne** [comment]
Maybe just take a picture using remote desktop, with cmd showing the hostname on each?

**Comment by echadbourne** [comment]
Update, I added proof so no need to worry about that
